FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /Solution
COPY TransactionalMassTransit .
RUN dotnet publish TransactionalMassTransit.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT dotnet TransactionalMassTransit.dll